### ISSUE TITLE
padStart is not a function

### ISSUE THREAD

**Issue by xdamman** [cheeaun/earth#1]
This looks phenomenal. Great job!

I just tried but I run into this issue when running `yarn geojson` (that is run by `yarn checkins`)

```
    const month = ('' + (_datetime.getMonth()+1)).padStart(2, '0');
                                                  ^
TypeError: ("" + (_datetime.getMonth(...) + 1)).padStart is not a function
    at geojson.features.data.map (/earth/scripts/geojson-checkins.js:17:51)
```
I have yarn 0.27.5 if that matters.

Any idea?

**Comment by xdamman** [comment]
Solved it. I was running node v6. It works with node 8.1.3

**Comment by xdamman** [comment]
FYI I also had to run `brew install svgo` to be able to run `yarn countries` (on MacOSX)

**Comment by cheeaun** [comment]
@xdamman oh wow, thanks! Forgot to add that to readme 😅  Will add it now
